
export const DATA_REQUEST = "DATA_REQUEST"
export const DATA_SUCCESS = "DATA_SUCCESS"
export const DATA_FAILURE = "DATA_FAILURE"

export const DATA_POST_REQUEST = "DATA_POST_REQUEST"
export const DATA_POST_SUCCESS = "DATA_POST_SUCCESS"
export const DATA_POST_FAILED = "DATA_POST_FAILED"


export const DATA_UPDATE_REQUEST = "DATA_UPDATE_REQUEST"
export const DATA_UPDATE_SUCCESS = "DATA_UPDATE_SUCCESS"
export const DATA_UPDATE_FAILED = "DATA_UPDATE_FAILED"

export const DATA_DELETE_REQUEST = "DATA_DELETE_REQUEST"
export const DATA_DELETE_SUCCESS = "DATA_DELETE_SUCCESS"
export const DATA_DELETE_FAILED = "DATA_DELETE_FAILED" 